# Site settings
title: Jose Izquierdo
email: jainguns@gmail.com
description: "Documentation, code snippets, and how to guides"
# baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jose-izquierdo.github.io" # the base hostname & protocol for your site
twitter_username: _abnz
github_username:  jose-izquierdo

# Owner/author information
owner:
  name: Jose Izquierdo
  avatar:         
  bio:            
  email:     
